### ISSUE TITLE
Love it! How to pre-fill?

### ISSUE THREAD

**Issue by jbdw85** [ditdot-dev/vue-flow-form#101]
Love the look and feel of this! How is it possible to pre-fill based on URLSearchParams?

**Comment by spinn** [comment]
Thanks!

In theory, this should have already been possible, but it will require a small fix unfortunately (coming in the next version). You'll be able to do this by setting the `answer` param on `QuestionModel`, eg.:

```js
const q = new URLSearchParams(window.location.search);

const questions = [
  new QuestionModel({
    answer: q.get('name'),
    ...
  })
];
```

If you're using the GitHub example project, this is already commited: 
https://github.com/ditdot-dev/vue-flow-form/commit/c2eef29e8145ebcaedd3cdf1843495a323331adb
