### ISSUE TITLE
Feature request: Positive validation notes for each entry

### ISSUE THREAD

**Issue by kygwang** [ditdot-dev/vue-flow-form#129]
**Is your feature request related to a problem? Please describe.**
I love it when apps are encouraging to the user and adds gamification elements. One such element that is useful is the idea of positive validation. So that after each user's input, there's a comment that shows up like "that's great!". 

**Describe the solution you'd like**
In the QuestionModal instance, include a new feature where devs can add positiveValidation: to incorporate a specific positiveValidation for each multipleChoice answer, or a single text response.  

**Describe alternatives you've considered**
Animation with a positive reinforcement sound that is activated after each question. Although this is a slightly more complex to integrate. 

**Additional context**
We're building an app right now to help users understand financial & tax issues for the gig economy. Many of them find this topic highly anxiety inducing and thus would want to encourage them with these positive validation notes. This is likely applicable for many other topics that are challenging or complex as well. eg. healthcare / legal.

**Comment by EkaterinaVu** [comment]
The concept of the application is that the positive validation is displayed in the next step. There are several ways to accomplish it (SectionBreak question type or on the tagline, for example). We do not plan to incorporate positive validation on the question itself. The goal is that the user interaction stays as simple, fast, and easy-to-fill.

Soon, we plan to implement on-progress (after each step) custom events, so there will be more options in this regard (e.g. custom events fired based on the user responses).

**Comment by kygwang** [comment]
That makes sense. Thank you for sharing that future feature release.

Ok to close this issue then.
