### ISSUE TITLE
Feature request: Datepicker type question

### ISSUE THREAD

**Issue by viraj-nikam** [ditdot-dev/vue-flow-form#130]
**Is your feature request related to a problem? Please describe.**
An additional question type for date picker would be great in scenarios where dates are required like birthdates.

**Describe the solution you'd like**
A simple date picker might work. Alternatively, the existing dropdown question might be tweaked to act like date, month and year dropdown selection.

**Comment by phre1** [comment]
Support for input type date has been implemented. More info can be found in our guide.
https://www.ditdot.hr/en/docs/vue-flow-form-guide#question-types
