### ISSUE TITLE
Feature request: Multi-input question type

### ISSUE THREAD

**Issue by mgd722** [ditdot-dev/vue-flow-form#131]
**Is your feature request related to a problem? Please describe.**
Sometimes a question requires more than one input to be answered. For example, I am writing a tax calculator and I need to account for both you and your partner's responses to what are essentially the same questions. For example:

Currently I ask:
- What is your monthly income?
- What is your partner's monthly income?

I have 10 questions like this, but with a partner it is doubled so married users have to answer 20 questions while single users only answer 10.

**Describe the solution you'd like**
Allow a multi-input question type that accepts inputs from multiple number or text inputs.

Example:
- What is your monthly income?
`You: <number input for your monthly income>`
`Partner: <number input for your partner's monthly income>`

**Describe alternatives you've considered**
Currently I do this as two separate questions. I understand that having two inputs on the same page isn't as clean as one input per page, but this seems like the lesser of two evils.

**Additional context**
I love the library so far!

**Comment by a2902793** [comment]
+1

**Comment by 484-studio** [comment]
Not sure it'd be exactly related to this, but I feel it could be:
Would love if multiple choice questions could show an input/URL field if selected. 

**Use case:**
Having a user select options from 'Which social medias do you use?' with the option to add a link on the ones they've selected

**Comment by yuvi100** [comment]
+1

Is this multiple questions per "slide" something that is in the pipeline?

**Comment by arthur-es** [comment]
I would love to see this feauture in this lib! I also need to ask more than one question (text input) sometimes...for example when asking for the address...It would be great to ask for the street name, zip code, number, in a single "slide/page"

**Comment by danielcharrua** [comment]
any updates on this feature?

**Comment by EkaterinaVu** [comment]
When we first designed Vue Flow Form, it was not intended to display multiple questions per screen and currently this feature is not at the top of our priority list. We are aware that this is a highly-requested feature though, so in case you want to contribute to this project, your help is very welcome.

**Comment by chrisformula** [comment]
Has anyone added this feature?
