### ISSUE TITLE
Feature request: Allow values to be booleans

### ISSUE THREAD

**Issue by mgd722** [ditdot-dev/vue-flow-form#134]
**Is your feature request related to a problem? Please describe.**
This is a fairly common scenario:
```
new ChoiceOption({
    label: 'yes',
    value: true
}),
new ChoiceOption({
    label: 'no',
    value: false
})
```
I have a yes/no question and I would like the answer to be a boolean so that I don't need to coerce it to a boolean later. Currently, doing this results in this error:

`[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, Array, got Boolean with value true.`

[Because of the way the `value` prop is configured in `Question.vue`.](https://github.com/ditdot-dev/vue-flow-form/blob/master/src/components/Question.vue#L131).

**Describe the solution you'd like**
Allow booleans to be accepted as values.

**Describe alternatives you've considered**
`let booleanAnswer = question.answer === 'true' ? true : false`

**Comment by mgd722** [comment]
`Number` would also make a lot of sense.

 **How many pets do you have?**

- One `<value:1>`
- Two `<value:2>`
- Three `<value:3>`

This would be way more graceful than having to coerce string values to `Number` after the fact.

**Comment by EkaterinaVu** [comment]
Support for Boolean to be accepted as value for prop "value" has been implemented.

**Comment by mgd722** [comment]
I'm not sure this 100% fixed it. This works ONLY for the `true` value:
```vue
new ChoiceOption({
	label: 'yes',
	value: true
}),
new ChoiceOption({
	label: 'no',
	value: false
})
```
so if you have a series of questions all the 'yes' answers evaluate to `true`, but all the 'no' answers still evaluate to `'no'`. Am I missing something?

**Comment by mgd722** [comment]
Same problem happens if I use `1` and `0` instead of `true` and `false`-- the `1`s evaluate, but `0`, being a falsy value, returns the string of the `label` instead.

**Comment by mgd722** [comment]
[The `choiceValue` method of the `ChoiceOption` class still does not allow falsy values](https://github.com/ditdot-dev/vue-flow-form/blob/master/src/models/QuestionModel.js#L48-L50).

**Comment by mgd722** [comment]
I have a PR to actually fix this, but I want to make sure it gets tested before it makes it into the mainstream.
