### ISSUE TITLE
Bug: Year input in pull request Feature/date input field #132

### ISSUE THREAD

**Issue by viraj-nikam** [ditdot-dev/vue-flow-form#141]
**Describe the bug**
The first digit of the year input gets overwritten by the second when using the keyboard to input

**To Reproduce**
When entering a year (eg. 1993)
1. Starting state of year input. (**yyyy**)
2. Enter the first input. **(0001)**. Press '1' key on the keyboard
3. Enter the second input. **(0009)**. Press '9' key on the keyboard

**Expected behaviour**
After entering the second input the state should look like this **(0019)**

**Screenshots**
![image](https://user-images.githubusercontent.com/46310063/99877124-f4f26000-2c21-11eb-94b1-acd3acff3ed3.png)

**Desktop (please complete the following information):**
 - Device: Dell Inspiron Laptop
 - OS: Windows 10 Home
 - Browser: Chrome

**Comment by spinn** [comment]
We weren't able to reconstruct your exact issue, but we did find issues with focus states on QuestionType.Date (see commit: https://github.com/ditdot-dev/vue-flow-form/commit/a6f4024ed9d4f9bdafee44265bfebbf51a75e5f0). This will be included in the next release, but in the meantime, you can try cloning the GitHub repo to see if this fixed your issue as well (I believe it should have).
