### ISSUE TITLE
Feature request: Show question if 'x'

### ISSUE THREAD

**Issue by 484-studio** [ditdot-dev/vue-flow-form#142]
**Is your feature request related to a problem? Please describe.**
Currently, paths feel 1 dimensional. It'd be great if questions could be displayed if certain things occur.

**Describe the solution you'd like**
QuestionModel option 'showIf' with values relating to previous answers. 
Eg:
new QuestionModel({
  id: 'multiple_choices',
  type: QuestionType.MultipleChoice,
  multiple: true,
  options: [
    new ChoiceOption({
      label: 'Answer 1'
    }),
    new ChoiceOption({
      label: 'Answer 2'
    })
  ]
}),
new QuestionModel({
  id: 'answer_1',
  showIf: 'multiple_choices.answers.contains("Answer 1")
})

**Comment by spinn** [comment]
What you're describing can already be done with logic jumps. Logic jumps can also be defined with callbacks where you can define any logic. This does require your questions to be grouped in a logical way, but this is already the case with most forms.

```js
new QuestionModel({
  id: 'multiple_choices',
  type: QuestionType.MultipleChoice,
  multiple: true,
  options: [
    new ChoiceOption({
      label: 'Answer 1',
      value: 'answer_1'
    }),
    new ChoiceOption({
      label: 'Answer 2',
      value: 'answer_2'
    })
  ],
  jump: function() {
    if (!this.answer.includes('answer_1')) {
      return 'skip_answer_1'
    }
  }
}),
new QuestionModel({
  id: 'answer_1',
  ...
}),
new QuestionModel({
  id: 'skip_answer_1'
  ...
})
```
