### ISSUE TITLE
Feature request: QuestionType.Number should return a number instead of a string

### ISSUE THREAD

**Issue by mgd722** [ditdot-dev/vue-flow-form#147]
**Is your feature request related to a problem? Please describe.**
`QuestionType.Number` answers are returned as strings, despite them only allowing users to enter numbers. 

**Describe the solution you'd like**
I think it would make more sense and be more useful to return a `Number` type instead. For example:

How many pets do you have?
- `<QuestionType.Number>`

If a number is returned, I could use it _either_ in a string _or_ for mathematics and both will work:

```
let sentence = `Wow, ${question.answer} pets is a lot!`

let pawCount = question.answer * 4
```

**Describe alternatives you've considered**
I currently have to parse all these answers to numbers, but since they can only ever be numbers they should just be automatically returned that way.

**Comment by spinn** [comment]
Thanks for the bug report - this has been fixed in commit 54bb8ecb88e09aa46f74c06a03416aa7e26f414e
