### ISSUE TITLE
Feature request:  Programmatic Navigation Between Questions

### ISSUE THREAD

**Issue by Waterloo** [ditdot-dev/vue-flow-form#162]
**Is your feature request related to a problem? Please describe.**
Currently, Flow form doesn't have an option to navigate between questions and sections programmatically, this will be useful when using it along with Vue-router or any other Vue components and libraries. 

**Describe the solution you'd like**
Add a method to navigate between questions based on a key or index in the questions array.

**Comment by spinn** [comment]
Thanks for the suggestion, we think it's a good idea and will make sure to add this in a future version.

**Comment by spinn** [comment]
To do this, you need to register a reference to the FlowForm component and use the `goToNextQuestion` and `goToPreviousQuestion` methods, eg.:

```vue
<template>
  <flow-form
    ref="flowform"
    :questions="questions"
  ></flow-form>
</template>

<script>
  export default {
    components: {
      FlowForm
    },

    data() {
      return {
        questions: []
      }
    },
    
    mounted() {
      // Go forwards if the next question is available
      this.$refs.flowform.goToNextQuestion()

      // Go backwards if the previous question is available
      this.$refs.flowform.goToPreviousQuestion()
    }
  }
</script>
```
