### ISSUE TITLE
Bug:mask with array

### ISSUE THREAD

**Issue by matheusf31** [ditdot-dev/vue-flow-form#166]
**Describe the bug**
If I use the mask in `new QuestionModel` with an array like this: `mask: ['###.###.###-##', '###.###.###/#####']` the input don't work appropriately. They recognize just 2 numbers and don't recognize the format of the mask that was expected (###.###.###-## or ###.###.###/#####).

**To Reproduce**
Clone and run the vue-flow-form and in file **examples/questionnaire/Example.vue** change the **fisrt** question to this:

```
new QuestionModel({
  id: 'first_name',
  tagline: 'Hi! Welcome to our demo survey 😊',
  title: 'CPF?',
  type: QuestionType.Phone,
  required: true,
  mask: ['###.###.###-##', '###.###.###/#####'],
}),
```

**Expected behavior**
I expect to be able to press ok if the format is correct in the both cases of the mask (###.###.###-## **or** ###.###.###/#####).

**Screenshots**
![image](https://user-images.githubusercontent.com/45342938/108223647-c7ca2680-7118-11eb-93fd-f1d78b1c051f.png)
![image](https://user-images.githubusercontent.com/45342938/108223695-d3b5e880-7118-11eb-8733-c874806ca561.png)
![image](https://user-images.githubusercontent.com/45342938/108223748-e3cdc800-7118-11eb-907d-bd65c0c9f6a2.png)
![image](https://user-images.githubusercontent.com/45342938/108223778-ecbe9980-7118-11eb-8025-3e181abc12b0.png)

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: chrome
 - Version: 88.0.4324.150 64 bits

**Comment by spinn** [comment]
Thank you for the extensive bug report and the example you provided. This issue has been fixed in commit 3fedfcd02722b98ef43456db990592f69375fb69, but this change now unfortunately revealed a bug in vue-the-mask:

https://github.com/vuejs-tips/vue-the-mask/pull/64

We'll either have to find a suitable replacement for vue-the-mask, or fork it to fix the issue.
