### ISSUE TITLE
Bug: Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by Amaan630** [ditdot-dev/vue-flow-form#177]
**Describe the bug**
Whenever I try to use the package, I get the following error in my console:
`Uncaught (in promise) TypeError: Cannot read property '_c' of undefined`
I tried each of the examples and get the error with each of them. I'm on Vue 3.0.5 and I'm using it with Laravel, I'm not sure if that makes a difference. What confuses me the most is that I had this working on an earlier project just fine.

**To Reproduce**
Copy and paste one of the examples and try to refresh the page, I see this error in the console.

**Desktop (please complete the following information):**
 - Device: Macbook pro 2015
 - OS: macOS big sur
 - Browser chrome

**Comment by EkaterinaVu** [comment]
Hi @Amaan630, 
this is most likely related to the fact you are using Vue 3. We are not supporting Vue 3 at this time, but we plan to, probably starting with the next release.

**Comment by Amaan630** [comment]
Okay, thank you!

**Comment by Amaan630** [comment]
Sorry to ask another question in this thread, but any idea when the next release might be coming? I love the package and can't wait to use it!

**Comment by EkaterinaVu** [comment]
@Amaan630, 

we are trying our best to release the new versions as frequent as we can. Since the latest version was released relatively recently, it will probably take at least a month until the next one.
