### ISSUE TITLE
bug :  questions after jump not excluded

### ISSUE THREAD

**Issue by webwakko** [ditdot-dev/vue-flow-form#178]
Hi,

I noticed that, when using the jump-option, there is a slight issue for the answers that follow.
example:

first question (Q1) has 2 possible options : A or B
When choosing A, you need to fill in Q2, Q3, Q4, Q7 > submit
When choosing B, you jump to Q5, Q6, Q7 > submit
the issue is that option A is also taking Q5 & Q6 in account, which is only for B answer

How can I avoid that QuestionModels are dedicated for certain option?

**Comment by webwakko** [comment]
FYI : would be nice if you could have something like typeform that says .. "no matter which answer, jump to Qx .. 
So if you want people to jump from Q2 to Q4..  there should be an option that "nextQuestionJump :  Q4"
if this is not set, go from Q2 to Q3..

**Comment by spinn** [comment]
Hi,

logic jumps are intended to be relatively simple logic jumps that jump to another question depending on the answer. This is intended to skip a group of questions depending on the user's answer (eg. skip questions 2 and 3 if answer to question 1 is "A"). 

To do what you want, you'd either need to re-order your questions a bit (maybe even duplicate the one that's related to both questions). or you could pass a callback to Vue Flow Form as the jump parameter:

https://www.ditdot.hr/en/docs/vue-flow-form-guide#global-options

Jump callbacks could also be used for your second question (simply return the ID for Q3 after any answer on Q1). Although in this case you could remove Q2 entirely if it's not supposed to be ever displayed.

**Comment by webwakko** [comment]
Hi, 

tnx for the quick answer. 
I noticed a little error in the way I explained my issue : 

A has 2 options : 1 or 2
When 1 : the order of questions is B C D F
When 2 : the order of questions is E F
So, 1 can never have E in the list, which does happen
and 2 can never have BCD, which is no issue.
The issue lies within the flow if there is no jump.. it takes a question that is only intented for option 2.

**Comment by webwakko** [comment]
>or you could pass a callback to Vue Flow Form as the jump parameter:
> 
> https://www.ditdot.hr/en/docs/vue-flow-form-guide#global-options
> 
> Jump callbacks could also be used for your second question (simply return the ID for Q3 after any answer on Q1). Although in this case you could remove Q2 entirely if it's not supposed to be ever displayed.

The issue with the jump is that this is only good for questions that have multiplechoice... or when you know which answer people will give..  I Itried the _other option so that it would jump, but that was a bad choice, it made my app crash :s

**Comment by webwakko** [comment]
SOLVED !
Duplicated the questions that needed response in both cases (1 OR 2)
but at the end of each duplicated question I added the _other submit.. so it avoids dropping to the question that was mentioned afterwards.
I also removed all items that had no answer.. so it would no polute my db with questions without answers (if option A was  1 it posted the empty question for option 2)
