### ISSUE TITLE
Bug: The screen starts to shake after typing an answer on Android devices.

### ISSUE THREAD

**Issue by arthur-es** [ditdot-dev/vue-flow-form#184]
**Describe the bug**
When using an android device (it does not happen o iOS) the screen blinks/shakes whenever we finish typing a answer. I've demontrated that behavior on the video attached.

**To Reproduce**
1 - Clone the repo.
2 - Start the project.
3 - Open any example
4 - Type the answer

**Expected behavior**
I expect the screen not to blink/shake.

**Screenshots**
I've uploaded a video.

**Desktop (please complete the following information):**
 - Device: REDMI 8, SAMSUNG GALAXY S10e, Motorola G5,G6
 - OS: Android
 - Browser: Chrome (it works just fine on firefox)
 - Version: most recent

**Additional context**
Video:
https://user-images.githubusercontent.com/37699234/112041090-bfed1000-8b24-11eb-9a95-831d84993a2b.mp4

**Comment by spinn** [comment]
Thank you for the extensive bug report, description and video. This has been fixed in da4709665d68e383355f2300b17cc557d38897f3.
