### ISSUE TITLE
How to include a custom submit screen when you use straight Javascript.

### ISSUE THREAD

**Issue by TheBitmonkey** [ditdot-dev/vue-flow-form#187]
This is great.. but I do not know how to load a custom completed screen through Javascript. I have tried every combination by now and nothing seems to work.

**Comment by spinn** [comment]
I've prepared a small CodePen for you (this is the support page example but using straight JavaScript):

https://codepen.io/DITDOT/pen/rNjZGgq

Hope this helps, but if not of course feel free to ask any additional questions.
