### ISSUE TITLE
Ranking Questionnaire from most to least

### ISSUE THREAD

**Issue by AjayShanker-geek** [ditdot-dev/vue-flow-form#197]
It would be great if possible to rank answers from most to least. It is helpful in getting an accurate response from Users. Is it possible to warp QuestionType with Vue.Draggable or Sortable.js. Sorry I am new to Vue js so I don't know if it is possible.

**Comment by spinn** [comment]
Hi @AjayShanker-geek,

this is currently not possible but is definitely an interesting idea which we'll consider as a possible new feature in future updates.

**Comment by AjayShanker-geek** [comment]
Sure, looking forward!

Cheers
