### ISSUE TITLE
Feature request: File upload

### ISSUE THREAD

**Issue by jimbrew** [ditdot-dev/vue-flow-form#201]
Do you have any plans to support uploading files.

Thank you.

**Comment by spinn** [comment]
Hi @jimbrew,

we do, it's actually currently in development and should be ready shortly. I'm not sure when we'll build a new npm version, but it will be available in the GitHub version.

**Comment by spinn** [comment]
This has now been merged to the master branch, the type is `QuestionType.File`, it's used in the same way as the other question types. Just make sure you're using FormData when sending the data to the back-end, eg.:

```
function onSubmit(questionList) {
  // Handle submit event. 
  const formData = new FormData()
  
  questionList.forEach(question => {
    formData.append(question.id, question.answer)
  })

  fetch(url, {
    method: 'POST',
    body: data
  })
}
```

**Comment by jimbrew** [comment]
@spinn Awesome thank you very much

**Comment by jimbrew** [comment]
@spinn Is this available via NPM?

**Comment by spinn** [comment]
@jimbrew Not yet, we're usually publishing one version per month, we want to make sure that when we publish it's as stable and bug-free as can be.

If you pull the latest Git version, you can run the following command to build the npm version:

```sh
npm run build:npm
```

Which you can then add as a local dependency to your project, eg.:

```sh
npm install ../vue-flow-form
```
