### ISSUE TITLE
Bug: jump on past question

### ISSUE THREAD

**Issue by beres** [ditdot-dev/vue-flow-form#206]
**Describe the bug**
I need the ability to jump back on past questions, but Firefox or Chrome crash after press "ok".

I tried to update support example, simply add a jump to "multiple choice" adding the choice faq_yes.

As i say the browser hangs for a while, and fater crash the tab. No one message or error appers on the console.

I've also try creating a questionare with QuestionModel() but the results is the same. Is it a bug or i'm make some mistake?

**To Reproduce**
this is the questions array 
https://pastebin.com/GcN8B74B

**Comment by spinn** [comment]
Hi @beres,

thank you for the bug report. The latest Github version now has a fix for that issue and you can safely jump to previous questions. We also added a new API function which allows jumping to any question in the form (when possible of course), you can see an explanation of how it works here:

https://github.com/ditdot-dev/vue-flow-form/issues/205#issuecomment-872442113
