### ISSUE TITLE
CSS for minimal theme not applied on mobile

### ISSUE THREAD

**Issue by camhart** [ditdot-dev/vue-flow-form#207]
I'm finding that the css for minimal is applied properly on desktop but not mobile devices.

I'm using this with vuetify.

**Comment by camhart** [comment]
For anyone else facing this, I copied the contents of the following files into my vue components style tag and that fixed it.
* https://github.com/ditdot-dev/vue-flow-form/blob/master/src/assets/css/common.css
* https://github.com/ditdot-dev/vue-flow-form/blob/master/src/assets/css/themes/theme-minimal.css

**Comment by spinn** [comment]
Hi @camhart,

can you provide any additional details? I just tried in a blank Vuetify project (both with v2 and v3) and haven't had any issues.

Could you maybe provide a simple sample project that would help us diagnose this issue? Thanks.

**Comment by spinn** [comment]
Closing the issue due to inactivity, but of course feel free to open it back up if you're still having problems.
