### ISSUE TITLE
Feature request: Making autofocus optional

### ISSUE THREAD

**Issue by mesuthabibpasa** [ditdot-dev/vue-flow-form#208]
**Is your feature request related to a problem? Please describe.**
Autofocus makes mobile users' life harder when text is long enough.

**Describe the solution you'd like**
It would be nice to have the option to disable autofocus

**Describe alternatives you've considered**
Declaring a function to clear focus on the "step" event can also solve the problem however step event is not fired for the first question displayed I guess

**Comment by spinn** [comment]
Hi @mesuthabibpasa,

thank you for your feature request. This has been implemented in this commit: 93bad194fc77722b424383a5080e345f9d4aaf10. It will of course also be included when we build the new npm version.
