### ISSUE TITLE
Bug: Skipping longtext question on mobile devices shows blank page

### ISSUE THREAD

**Issue by coxlr** [ditdot-dev/vue-flow-form#216]
**Describe the bug**
When a longtext question has required set as false as show below, when clicking skip the next question is not show and a blank page is displayed. This occurs when using the question component, as used in the support page example.

```
{
            type: 'longtext',
            id: "faq_no",
            tagline: 'Submit issue > Step 2/3',
            title: 'Please describe your problem.',
            required: false,
            placeholder: 'Start typing here...',
            model: ''
},
```

**To Reproduce**
For the support-page example in Example.vue set the longtext question to use required as false, and add an additional question that follows this question. Then click skip for this question when completing the survey and it display a blank page and not the expected question.

**Expected behavior**
The next question should be displayed in the same way it is when the question is answered and not skipped.

**Screenshots**
Here is a video showing what currently happens. I have set the longtext question to use required as false, and add an additional question that follows this question on the support-page example.

https://user-images.githubusercontent.com/8451762/134442501-eb88bea0-b60b-44ba-8a07-f82e72cba4b8.mov

**Desktop (please complete the following information):**
Device: MacBook Pro
OS: IOS
Browser chrome using devtools as a mobile device
Version 93.0.4577.82 (Official Build) (x86_64)

Also tested and experience the same issue on the following mobile device:
Device: iPhone 12 mini
OS: IOS 14
Browser chrome and safari

**Comment by spinn** [comment]
Hi @coxlr,

thanks for the detailed bug report - your issue has been fixed in 2a22e0a1dcd3b7f0d8e8040021f5f5c5192f8739 and will be included in the next npm build.
