### ISSUE TITLE
Feature request: slot **BeforeStart**

### ISSUE THREAD

**Issue by nikolaysm** [ditdot-dev/vue-flow-form#222]
Hi 👋 ,

Thanks for creating and sharing this great project!

It will be useful to add a slot **BeforeStart** or allow for `QuestionType.SectionBreak` > `content` to use `html (v-html)`?

**Comment by nikolaysm** [comment]
https://github.com/ditdot-dev/vue-flow-form/blob/02f307d00a6cf2e004f898a470977f22b79a1eab/src/components/QuestionTypes/SectionBreakType.vue#L3


Instead we can use

`<span class="f-section-text" v-html="question.content"></span>`

**Comment by spinn** [comment]
Hi @nikolaysm,

we already had a similar request and decided against it, you can see our reasoning here:

https://github.com/ditdot-dev/vue-flow-form/pull/108#issuecomment-693553925

For now we don't plan on adding HTML support but we'll consider adding this in a future version.

**Comment by nikolaysm** [comment]
Hi @spinn , 

Thanks for your reply!

How about `slot` **BeforeStart** similar as: https://github.com/ditdot-dev/vue-flow-form/blob/02f307d00a6cf2e004f898a470977f22b79a1eab/src/components/FlowForm.vue#L24

**Comment by spinn** [comment]
Questions can be defined both via the `questions` prop or as components so we'd need a solution that works in both cases. But as I said, we'll definitely take this into consideration and try to find a solution for a future release.
