### ISSUE TITLE
Feature request: Make it simpler to change basic styles such as font-size

### ISSUE THREAD

**Issue by vesper8** [ditdot-dev/vue-flow-form#236]
I'm trying to make a quiz fit inside a narrow box and am having a lot of trouble identifying what needs to be changed in order to reduce things like font-size and expand things like the width of boxes. It would be great if you had a styling guide available that explained what needs to be edited for these kinds of common changes.

Loving the package otherwise, very useful and flexible

**Comment by EkaterinaVu** [comment]
Hi @vesper8, 

you can find all common (not related to the specific theme) CSS rules in the src/assets/css/common.css file. For example, font size is defined in lines 17 to 41. We tried to make our CSS as minimal and flexible as it gets.
 
You can also create your own, custom theme https://www.ditdot.hr/en/docs/vue-flow-form-guide#custom-theme and/or use non-standalone layout https://www.ditdot.hr/en/docs/vue-flow-form-guide#layout , if applicable.
