### ISSUE TITLE
in javascript mode, completeButton slot does not work

### ISSUE THREAD

**Issue by vesper8** [ditdot-dev/vue-flow-form#237]
I tried both your Vue 2 and Vue 3 version. When using the example code you provide to set it up via a simply `index.html` + `app.js`, everything works fine including the use of the `complete` slot, but the `completeButton` slot is completely unrecognized and has no effect at all

**Comment by EkaterinaVu** [comment]
Hi @vesper8 , 

We tried the code below and everything works as intended.  If the issue persists, please provide us with some details such as code examples and expected behavior so we could reproduce the problem.

HTML:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- Requires Vue version 3.x -->
    <script src="https://unpkg.com/vue@next"></script>
    <!-- Flow Form -->
    <script src="https://unpkg.com/@ditdot-dev/vue-flow-form@2.2.1"></script>
    <!-- Flow Form base CSS -->
    <link rel="stylesheet" href="https://unpkg.com/@ditdot-dev/vue-flow-form@2.2.1/dist/vue-flow-form.min.css">
    <!-- Optional theme.css -->
    <link rel="stylesheet" href="https://unpkg.com/@ditdot-dev/vue-flow-form@2.2.1/dist/vue-flow-form.theme-minimal.min.css">
    <!-- Optional font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;900&amp;display=swap">
  </head>
  <body>
    <div id="app"></div>
    <script src="app.js"></script>
  </body>
</html>
```
JavaScript (content of app.js):
```js
var app = Vue.createApp({
  el: '#app',
  template: `
    <flow-form v-bind:questions="questions" v-bind:language="language">
      <template v-slot:completeButton>
        <h3>Button content</h3>
      </template>
    </flow-form>
  `,
  data: function () {
    return {
      language: new VueFlowForm.LanguageModel({
        // Your language definitions here (optional).
        // You can leave out this prop if you want to use the default definitions.
      }),
      questions: [
        new VueFlowForm.QuestionModel({
          title: 'Question',
          type: VueFlowForm.QuestionType.MultipleChoice,
          options: [
            new VueFlowForm.ChoiceOption({
              label: 'Answer'
            })
          ]
        })
      ]
    }
  }
}).component('FlowForm', VueFlowForm.FlowForm);

const vm = app.mount('#app');
```

**Comment by vesper8** [comment]
@EkaterinaVu @phre1 

Apologies I should have been more clear about one thing. I've opted to not using the `template` directive and have my html directly inside the `index.html` since it's more convenient for allowing the editor to handle auto-indenting and colour highlighting.

All functionalities work fine when doing this except for the one I reported with the `completeButton` slot not working.

What's odd is that the `complete` slot DOES work, only the `completeButton` slot does not work.

Using the code you posted above, but commenting out the `template:` part from `app.js` and having an `index.html` file that looks like this:

```

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- Requires Vue version 3.x -->
    <script src="https://unpkg.com/vue@next"></script>
    <!-- Flow Form -->
    <script src="https://unpkg.com/@ditdot-dev/vue-flow-form@2.2.1"></script>
    <!-- Flow Form base CSS -->
    <link rel="stylesheet" href="https://unpkg.com/@ditdot-dev/vue-flow-form@2.2.1/dist/vue-flow-form.min.css">
    <!-- Optional theme.css -->
    <link rel="stylesheet" href="https://unpkg.com/@ditdot-dev/vue-flow-form@2.2.1/dist/vue-flow-form.theme-minimal.min.css">
    <!-- Optional font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;900&amp;display=swap">
  </head>
  <body>
    <div id="app">
      <flow-form v-bind:questions="questions" v-bind:language="language">
        <template v-slot:complete>
          complete
        </template>
        <template v-slot:completeButton>
          <h3>Button content</h3>
        </template>
      </flow-form>      
    </div>
    <script src="js/app-test.js"></script>
  </body>
</html>
```


When using the `template:` directive, both slots works, when putting the template inside `index.html`, only the `complete` slot works.


Any idea why that is?


Many thanks

**Comment by EkaterinaVu** [comment]
@vesper8 , 

it looks like the problem is caused by camel-cased slot name. Until we figure out how to solve this, you can try the workaround  - add `buttonslot: 'completeButton' `  to `data` in `app.js ` an then use it inside `index.html` like this:

```html
 <template v-slot:[buttonslot]>
   <h3>Button content</h3>
 </template>
```

**Comment by vesper8** [comment]
@EkaterinaVu thank you, that does work.

I had also tried writing it like this but that didn't work `<template v-slot:complete-button>`
