### ISSUE TITLE
Question: how to set submitted manually in Vue 3 Composation Api

### ISSUE THREAD

**Issue by erkage** [ditdot-dev/vue-flow-form#242]
Hi,

I can't figure out, how I can set manually the `submitted` to true when using Vue 3 Composation Api!?

Thanks in advance!

**Comment by erkage** [comment]
and also the methods like `goToQuestion`?

**Comment by erkage** [comment]
For the others:
```
<template>
   <flow-form
      :questions="questions"
      ref="vff"
   >
</template>

<script setup>
   ...
   const vff = ref(null);
   ...
</script>
```
And then you can use for example `vff.value.goToQuestion(id)` or `vff.value.submitted = true`.

**Comment by mgd722** [comment]
old style:

```
this.$refs.vff.$data.submitted = true
```
