### ISSUE TITLE
Favorite movies section

### ISSUE THREAD

**Issue by ZeroTex** [ditdot-dev/vue-flow-form#95]
Isn't very mobile friendly on this specific section. A button should appear to add the movie and then perform the line break, followed by an X button to delete that movie from the list, etc.

**Comment by EkaterinaVu** [comment]
Yes, different behavior was needed on mobile for that question type, so we made a fix. Now, only on mobile, enter/return makes a line break, and helper text shift+enter is removed.
Your suggestion for an input chip with a remove 'button' feature is great, but that should be a separate question type, this one is a standard text area. We’ll add it to our further possible feature development list.
